### ISSUE TITLE
Coustom plugin not work

### ISSUE THREAD

**Issue by ghost** [RusherDevelopment/example-plugin#2]
Hi, I making my plugin but when I build it and I move jar in plugins folder /rusherhack/plugins/ plugin doesn't show up when I use *plugin command.
Code: https://github.com/Lubix88/BaseHuntTools 
I have -Drusherhack.enablePlugins=true argument

**Comment by John200410** [comment]
Does any error get printed in the console?
What command are you using to build the plugin?

**Comment by ghost** [comment]
> Does any error get printed in the console? What command are you using to build the plugin?

I use build task gradle
When i run mc i have error:
```
[16:33:13] [Render thread/INFO]: Initializing rusherhack v2.0-preview
[16:33:19] [Render thread/INFO]: [STDERR]: java.lang.ClassNotFoundException: me.lubix.bht
[16:33:19] [Render thread/INFO]: [STDERR]: 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
[16:33:19] [Render thread/INFO]: [STDERR]: 	at org.rusherhack.?.findClass(?.java:115)
[16:33:19] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
[16:33:19] [Render thread/INFO]: [STDERR]: 	at org.rusherhack.?.loadClass(?.java:84)
[16:33:19] [Render thread/INFO]: [STDERR]: 	at org.rusherhack.?.a(?.java)
[16:33:19] [Render thread/INFO]: [STDERR]: 	at org.rusherhack.?.?(?.java:129)
[16:33:19] [Render thread/INFO]: [STDERR]: 	at org.rusherhack.Ö.a(Ö.java)
[16:33:19] [Render thread/INFO]: [STDERR]: 	at org.rusherhack.Ö.Ő(Ö.java:57)
[16:33:19] [Render thread/INFO]: [STDERR]: 	at org.rusherhack.U.a(U.java)
[16:33:19] [Render thread/INFO]: [STDERR]: 	at org.rusherhack.U.<init>(U.java:238)
[16:33:19] [Render thread/INFO]: [STDERR]: 	at org.rusherhack.U.?(U.java:143)
[16:33:19] [Render thread/INFO]: [STDERR]: 	at org.rusherhack.mixin.MixinHelper.b(MixinHelper.java)
```

**Comment by John200410** [comment]
In the rusherhack-plugin.json file you only have your plugin's package, when its supposed to have the plugin's main class.
It should be me.lubix.bht.BhtPlugin

**Comment by ghost** [comment]
> In the rusherhack-plugin.json file you only have your plugin's package, when its supposed to have the plugin's main class. It should be me.lubix.bht.BhtPlugin

It working thanks
